######################################################################
# Automatically generated by qmake (1.06c) Thu Nov 11 11:55:42 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
