######################################################################
# Automatically generated by qmake (1.06c) Fri Nov 12 15:44:11 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h lcdrange.h
SOURCES += cannon.cpp lcdrange.cpp main.cpp
