######################################################################
# Automatically generated by qmake (1.06c) Fri Nov 12 16:03:35 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h lcdrange.h
SOURCES += cannon.cpp lcdrange.cpp main.cpp
