######################################################################
# Automatically generated by qmake (1.07a) Tue Mar 18 14:45:16 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
