######################################################################
# Automatically generated by qmake (1.06c) Wed Nov 17 15:06:43 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h lcdrange.h
SOURCES += cannon.cpp lcdrange.cpp main.cpp
