######################################################################
# Automatically generated by qmake (1.06c) Thu Nov 18 09:42:01 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cannon.h gamebrd.h lcdrange.h
SOURCES += cannon.cpp gamebrd.cpp lcdrange.cpp main.cpp
