######################################################################
# Automatically generated by qmake (1.06c) Thu Nov 11 15:36:26 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += lcdrange.h
SOURCES += lcdrange.cpp main.cpp
