######################################################################
# Automatically generated by qmake (1.06c) Thu Nov 11 13:07:16 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
